sunxi: CONFIG_SYS_MMC_ENV_DEV undeclared
bananapi_m64_defconfig with CONFIG_ENV_IS_NOWHERE results in:

    board/sunxi/board.c: In function 'mmc_get_env_dev':
    board/sunxi/board.c:535:24: error:
    'CONFIG_SYS_MMC_ENV_DEV' undeclared (first use in this function)
      535 |                 return CONFIG_SYS_MMC_ENV_DEV;
          |                        ^~~~~~~~~~~~~~~~~~~~~~

Check if CONFIG_SYS_MMC_ENV_DEV is defined.

Fixes: c38515e1e042 ("sunxi: Select environment MMC based on boot device")
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>